# Generated by Django 4.0.5 on 2022-06-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('appaterno', models.CharField(max_length=40)),
                ('apmaterno', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=10)),
                ('edad', models.CharField(max_length=3)),
                ('nombrevacuna', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
