# Generated by Django 4.0.5 on 2022-07-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuna_maule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('appaterno', models.CharField(max_length=40)),
                ('apmaterno', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
